{"name": "test_auth[hotenok_85@mail.ru-010885]", "status": "failed", "statusDetails": {"message": "AssertionError: assert not True\n +  where True = <bound method WebElement.is_visible of <pages.elements.WebElement object at 0x000002337EBF3DC8>>()\n +    where <bound method WebElement.is_visible of <pages.elements.WebElement object at 0x000002337EBF3DC8>> = <pages.elements.WebElement object at 0x000002337EBF3DC8>.is_visible\n +      where <pages.elements.WebElement object at 0x000002337EBF3DC8> = <pages.pages_auth.RTmis object at 0x000002337F7274C8>.error", "trace": "web_browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"af25a99caa3cc09a33a8e4272727942c\")>, login = 'hotenok_85@mail.ru', password = '010885'\n\n    @allure.feature('Авторизация на https://rtmis.ru/')\n    @allure.story('Тест с авторизации с рандомизируемыми данными')\n    def test_auth(web_browser, login:str, password:str):\n        web = RTmis(web_browser)\n    \n        with allure.step(f\"Открываем {web.url}\"):\n          web.get(url=web.url)\n        with allure.step(\"Заполняем форму (логин:пароль)\"):\n          assert web.login.send_keys(login)\n          assert web.password.send_keys(password)\n        with allure.step(\"Нажимаем на кнопку войти\"):\n          web.auth.human_click()\n        with allure.step(\"Определям на странице сообщение об ошибке авторизации\"):\n>           assert not web.error.is_visible()\nE           assert not True\nE            +  where True = <bound method WebElement.is_visible of <pages.elements.WebElement object at 0x000002337EBF3DC8>>()\nE            +    where <bound method WebElement.is_visible of <pages.elements.WebElement object at 0x000002337EBF3DC8>> = <pages.elements.WebElement object at 0x000002337EBF3DC8>.is_visible\nE            +      where <pages.elements.WebElement object at 0x000002337EBF3DC8> = <pages.pages_auth.RTmis object at 0x000002337F7274C8>.error\n\ntests\\test_auth.py:18: AssertionError"}, "steps": [{"name": "Открываем https://demo.rtmis.ru/", "status": "passed", "start": 1643733440455, "stop": 1643733444709}, {"name": "Заполняем форму (логин:пароль)", "status": "passed", "start": 1643733444709, "stop": 1643733444834}, {"name": "Нажимаем на кнопку войти", "status": "passed", "start": 1643733444834, "stop": 1643733455240}, {"name": "Определям на странице сообщение об ошибке авторизации", "status": "failed", "statusDetails": {"message": "AssertionError: assert not True\n +  where True = <bound method WebElement.is_visible of <pages.elements.WebElement object at 0x000002337EBF3DC8>>()\n +    where <bound method WebElement.is_visible of <pages.elements.WebElement object at 0x000002337EBF3DC8>> = <pages.elements.WebElement object at 0x000002337EBF3DC8>.is_visible\n +      where <pages.elements.WebElement object at 0x000002337EBF3DC8> = <pages.pages_auth.RTmis object at 0x000002337F7274C8>.error\n", "trace": "  File \"C:\\Users\\ole lukoie\\Desktop\\ui\\tests\\test_auth.py\", line 18, in test_auth\n    assert not web.error.is_visible()\n"}, "start": 1643733455240, "stop": 1643733455272}], "parameters": [{"name": "login", "value": "'hotenok_85@mail.ru'"}, {"name": "password", "value": "'010885'"}], "start": 1643733440455, "stop": 1643733455272, "uuid": "89d13cc1-bd2e-4de2-942b-8a4eb120401e", "historyId": "fcded4e3e4fc77ab668b7bda554e4064", "testCaseId": "5306df55395c93b83e69abe887b683bd", "fullName": "tests.test_auth#test_auth", "labels": [{"name": "feature", "value": "Авторизация на https://rtmis.ru/"}, {"name": "story", "value": "Тест с авторизации с рандомизируемыми данными"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "DESKTOP-2HIEP5G"}, {"name": "thread", "value": "1520-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}